accounts:
  - name: alice
    coins: ["1000token", "10000000000stake", "1cudosAdmin"]
  - name: bob
    coins: ["500token"]
validator:
  name: alice
  staked: "100000000stake"
client:
  vuex:
    path: "vue/src/store"
faucet:
  name: bob 
  coins: ["5token"]
genesis:
  app_state:
    gov:
      voting_params:
        voting_period: 30s
    bank:
      params:
        send_enabled:
          - denom: cudosAdmin
            enabled: false
